version: "3"
services:
  pyserver:
    container_name: torch-gpu
    build: .
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    volumes:
      - .:/workspace
    command: nvidia-smi
    working_dir: /workspace
    entrypoint: bash
    ports:
      - "8888:8888"
