version: "3"
services:
  pyserver:
    container_name: torch-gpu
    build:
      context: .
      dockerfile: Dockerfile
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
    ports:
      - "8888:8888"
    tty: true
    command: jupyter-lab --ip 0.0.0.0 --port=8888
